version: '3.8'

services:
  showdown:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app
    container_name: showdown
    command: yarn docker:start