version: '3.8'

services:
  showdown:
    environment:
      - CI=true
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: showdown
    command: npm run start